config/routes.rb
MUSG::Application.routes.draw do

  resources :true_shades, only: [:index, :new, :show, :create, :destroy, :edit] do
    resources :foundations, only: [:index, :new, :show, :create, :destroy, :edit] 
  end

   get 'true_shades/home' => 'true_shades#home', as: :home
   root 'about#about'

  resource :session, only: [:new, :create, :destroy]

  resources :users

end

app/models/foundation.rb
class Foundation 
  include Mongoid::Document

  field :show, type: String
  field :name, type: String
  field :brand, type: String
  field :product, type: String
  field :shade, type: String


  belongs_to :true_shade 
  has_many :users
  # has_many :users, through: :reviews

#   def users
#     Users.find( user_ids )
#   end

#   def user_ids
#     self.true_shades.map(&:user_id)
#   end
# # This is to write back a list of users we've gotten true_shades from
#   def user_ids=(list)
#   end
  
end

app/models/true_shade.rb
class TrueShade
  include Mongoid::Document
  field :name, type: String
  field :description, type: String


  has_many :users 
  has_many :foundations
end

# for choiceinator, decison is true shade and criteria is foundation  

app/models/user.rb
class User 
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :show, type: String
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String
  field :brand, type: String
  field :product, type: String
  field :shade, type: String
  field :true_shade_id, type: String

  validates :name, presence: true

  validates :email, presence: true
  validates_uniqueness_of :email

  validates :foundation_id, presence: true

  has_secure_password
  
  belongs_to :true_shade
  belongs_to :foundation
  # has_many :foundations, through: :reviews
end
 

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user 

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/foundations_controller.rb
class FoundationsController < ApplicationController
  # before_action :get_true_shade

  def index
    @foundations = @true_shade_id.foundations
  end

  def new
    @foundation = Foundation.new
  end  

  def create
    @foundation = Foundation.new(
      params.require(:foundation).permit(:true_shade, :brand, :product, :shade)
      )
    # Attach this criterion to a decision
    # user.foundation.true_shade = @true_shade
    foundation.true_shade = @foundation 
    if user.foundation.save
      redirect_to new_true_shade_foundations_path(@true_shade.id) 
    end
  end

  def show
    @foundation = Foundation.find(params[:id])
  end

  def edit
     @user = User.new(params.require(:user).permit(:brand, :product, :shade))
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to true_shade_path
    else 
      render 'new'
    end
  end

  def destroy
    Foundation.find(params[:id]).destroy
    redirect_to true_shade_foundations_path(@true_shade.id)
  end

# private
#   def get_true_shade
#     # Find our parent decision that we should attach to
#     @true_shade = TrueShade.find(params[:true_shade_id])
#   end

  # def check_security
  #   # If they're not logged in or they don't own this decision, boot them to the home page
  #   if (!current_user) || (@true_shade.user != current_user)
  #     redirect_to home_path
  #   end
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		# Present an empty login form
		@user = User.new
		@is_login = true
	end

	def create
		# Find the user that is trying to log in		
		u = User.where(email: params[:user][:email]).first
		if u && u.authenticate(params[:user][:password])
			# Store as a cookie in the users' browser the ID of them,
			# indicating that they are logged in
			session[:user_id] = u.id.to_s
			redirect_to users_path
		else
			# Go back to the login page
			redirect_to new_session_path
		end
	end 

	def destroy
		reset_session
		redirect_to new_session_path
	end
end

app/controllers/true_shades_controller.rb
class TrueShadesController < ApplicationController
  # before_action :get_true_shade


  def home
    @user = User.new
  end

  def index
    # @true_shades = TrueShade.all
    if !current_user
      redirect_to home_path
      return
    end 
    # @true_shades = TrueShade.where(user_id: current_user.id)
    @true_shades = current_user.foundation.true_shade
  end 

  def new
    if current_user
      @true_shade = TrueShade.new
    else
      redirect_to new_session_path
    end
  end

  def create
    # Make a new true shade object that is attached to the user
    true_shade = current_user.true_shade.new(params.require(:true_shade).permit(:name, :description))
    # With this decision object, attach it to the user
    # decision.user = current_user
    if true_shade.save
      redirect_to true_shades_path
    end
    # if !current_user
    #   redirect_to new_session_path
    #   return
    # end    
  end

  def show
    @true_shade = TrueShade.find(params[:id])
    @foundations = Foundation.all
    # @foundations = Foundation.find(params[:id])
  end

  def destroy
    TrueShade.find(params[:id]).destroy
    redirect_to true_shades_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  # prepare to show sign-up form
  def new
    @user = User.new
    @is_signup = true 
  end 
  # acutally build user
  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation, :foundation_id))
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to user_path(@user)
    else 
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
     @user = User.new(params.require(:user).permit(:brand, :product, :shade))
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to true_shade_path
    else 
      render 'new'
    end
  end

  def update
  end

  def destroy
    User.find(params[:id]).destroy
    # Exactly the same idea as this little number:
#    User.find_by(id: params[:id])
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/about.html.erb
<div class="container-fluid">

	<div class="row" id="welcome">
	  	<div class="col-md-12 welcome">
	  		<h1>MUSG</h1>
	  	</div>
	</div>
	<div class="row meet" id="meet" data-spy="scroll" data-target=".navbar">
	  	<h1>Welcome to Makeup Shade Guide</h1>
	  	<div class="col-md-4">
	  		<div class = "about"></div>
	  		<h3>Who Are We?</h3>
	  		<p>Makeup Shade Guide (MUSG for short) started as an idea to standardize the thousands of foundations into set "true shades" for women to make cosmetic shopping an easier and more pleasant experience. Users sign up, enter their current matching foundation shade(s), and MUSG will generate other matching foundations. This is achieved through crowd sourcing so the more users join, the more [accurate] the foundations will be. Try it out!</p> 		
	  	</div>
</div>

app/views/foundations/_form.html.erb
<%= form_for @foundation, html: { class: 'form' } do |f| %>
    <% if @foundation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@foundation.errors.count, "error") %> prohibited this foundation from being saved:</h2>

        <ul>
        <% @foundation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :brand %><br>
      <%= f.text_field :brand, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :product %><br>
      <%= f.text_field :product, class: 'form-control', required: true %>
    </div>

     <div class="form-group">
      <%= f.label :shade %><br>
      <%= f.number_field :shade, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.submit "Submit!", class: 'btn btn-primary btn-large' %>
    </div>
<% end %>

app/views/foundations/edit.html.erb
<h1> Edit this Foundation! </h1>

<%= render 'form' %>

<%= link_to 'Show', @foundation %> |
<%= link_to 'Back', true_shade_foundation_path %>

app/views/foundations/index.html.erb
<h1>My Matching Foundations</h1>

<ul>
<% @foundations.each do |f| %>
	<li>
		<%= link_to "f.name", true_shade_foundation_path(f) %> 
		
	</li>
<% end %>
</ul>

app/views/foundations/new.html.erb
<h1>Add a Foundation!</h1>

<br>form coming soon!</br>

app/views/foundations/show.html.erb
<h1>show me the foundation I clicked</h1>



<p>
  <strong>Brand:</strong>
  <%= @foundation.brand %>
</p>

<p>
  <strong>Product:</strong>
  <%= @foundation.product %>
</p>

<p>
  <strong>Shade:</strong>
  <%= @foundation.shade %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Makeup Shade Guide</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <!-- to look better on mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
	  <%= csrf_meta_tags %>
	</head>

	<body class="<%= params[:controller] %>">


		<%= render 'partials/nav' %>

		<div class="container">

			<%= yield %>

		</div>

	</body>


</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

     <!-- logo -->

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>


      <% if current_user %>

        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Hi, <%= current_user.name %>
          <span class="caret"></span>
        </a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to 'Log me out', session_path, method: :delete %>
            </li>
            <li class="divider"></li>
             <li>
              <%= link_to 'About Makeup Shade Guide', new_session_path  %> 
            </li>
          </ul>
        </li>

      <% else %>

        <li class="dropdown">

          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Log In or Sign Up
            <span class="caret"></span>
          </a>

          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to "Sign Up", new_user_path %>
            </li>
            <li>
              <%= link_to 'Log In', new_session_path  %> 
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'About Makeup Shade Guide', new_session_path  %> 
            </li>
          </ul>

        </li>



      <% end %>
        

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/true_shades/index.html.erb
<h1>TrueShade#index</h1>


<br>Your true shade is: <%= @user.foundation.true_shade.name %>
		<br><%= @user.foundation.true_shade.description %>
			<br><%= link_to "Click to see more foundations in your true shade", true_shade_path(@user.foundation.true_shade) %>

app/views/true_shades/new.html.erb
<h1>New True Shade#index</h1>

app/views/true_shades/show.html.erb
<h1>Show True Shade</h1>



<%= @true_shade.name %>
	<br><br>
	<ul>
		<% @foundations.each do |foundation| %>
			<% if foundation.true_shade == @true_shade %>
		<li>
			<%= link_to foundation.name, true_shade_foundation_path(foundation.true_shade.id, foundation.id) %>
		</li>
	<% end %>
	<% end %>
	</ul>



<br><%= link_to "Click to add another foundation in your true shade!!", new_true_shade_foundation_path(@true_shade, @foundation) %>
	

app/views/users/index.html.erb
<h1>User#index</h1>

Hi, <%= current_user.name %>

<br>See your saved foundations

<br>See your true shade

<br>Edit your account

app/views/users/new.html.erb
<center><br><h1>Find Your Matching Foundations! Sign up</h1>

<%= form_for @user do |u| %>
	<%= f.text_field :name, placeholder: "Name" %>
	<%= f.text_field :email, placeholder: "Email" %>
	<%= f.password_field :password, placeholder: "Password" %>
	<%= f.password_field :password_confirmation, placeholder: "One More Time" %>
	

	<br><br>Choose your current matching foundation <%= f.collection_select :foundation_id, Foundation.all, :id, :name %>
	<%= f.submit "Join Us" %>
<% end %></center>

<!-- f.text_field :brand, placeholder: "Current Matching Foundation Brand" %> -->
	<!-- f.text_field :product, placeholder: "Current Matching Foundation Product" %> -->
	<!-- f.text_field :shade, placeholder: "Current Matching Foundation Shade" %> -->

app/views/users/show.html.erb
<!DOCTYPE html>
	<head>
		<title>
		</title>
	</head>
	<body>

		<h1>Your True Shade</h1>
		<br>Your Current Matching Foundation: <%= @user.foundation.name %>
		<br>Your true shade is: <%= @user.foundation.true_shade.name %>
		<br><%= @user.foundation.true_shade.description %>
			<br><%= link_to "Click to see more foundations in your true shade", true_shade_path(@user.foundation.true_shade) %>

 
	</body>
</html>